---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: prometheus-crds
  namespace: kube-system
spec:
  repo: https://prometheus-community.github.io/helm-charts
  chart: prometheus-operator-crds
  targetNamespace: kube-prometheus
  createNamespace: true