apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      web:
        port: 8542
        exposedPort: 8542

      websecure:
        port: 8543
        exposedPort: 8543

    ingressClass:  # @schema additionalProperties: false
      enabled: true
      isDefaultClass: false
