---
apiVersion: v1
kind: Namespace
metadata:
  name: localstack
  labels:
    name: localstack   
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ls-pv-volume
  labels:
    type: local
spec:
  storageClassName: local-path
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data-ls"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ls-pv-claim
  namespace: localstack
spec:
  storageClassName: local-path
  volumeName: ls-pv-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Secret
metadata:
  name: localstack-credentials
  namespace: localstack
stringData:
  AWS_ACCESS_KEY_ID: fakekeyid
  AWS_SECRET_ACCESS_KEY: fakeaccesskey
  profile: |-
    [default]
    aws_access_key_id = fakekeyid
    aws_secret_access_key = fakeaccesskey  
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: localstack-settings
  namespace: localstack
data:
  AWS_REGION: us-east-1
  AWS_ENDPOINT_URL: http://localstack.localstack.svc.cluster.local:4566      
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: localstack
  namespace: kube-system
spec:
  repo: https://localstack.github.io/helm-charts
  chart: localstack
  targetNamespace: localstack
  version: 0.6.23
  createNamespace: true  
  set:
      startServices: "ses,sts,iam,secretsmanager,kms,ssm"
  valuesContent: |-
    image:
      repository: localstack/localstack
      tag: "4.3.0"
    service:
      type: LoadBalancer
    persistence:
      enabled: true
      existingClaim: ls-pv-claim
    mountDind:
      enabled: true
      forceTLS: false
    lambda:
      executor: docker
    extraEnvVars:
      - name: DEBUG
        value: "1"
      - name: ENFORCE_IAM
        value: "false"
      - name: LEGACY_DIRECTORIES
        value: "1"
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: localstack-credentials
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: localstack-credentials
            key: AWS_SECRET_ACCESS_KEY
