---
apiVersion: v1
kind: Namespace
metadata:
  name: reloader
  labels:
    name: reloader
---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: estakater-reloader
  namespace: flux-system
spec:
  repo: https://stakater.github.io/stakater-charts
  chart: reloader
  version: 2.1.3
  targetNamespace: reloader
  createNamespace: true  
